import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "src/styles/globals.css";

import classes from "./layout.module.scss";
import HeaderIconButton from "@/components/headerIconButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={classes.backgroundColor}>
        <header className={classes.AppBar}>
          <div className={classes.LeftSide}>
            <HeaderIconButton />
            <div className={classes.Typography}>
              <div className={classes.Title}>
                <div className={classes.Text}>タスク管理アプリ</div>
              </div>
            </div>
          </div>
        </header>
        <div className={classes.sideBar}>さいどヴァー</div>

        {children}
      </body>
    </html>
  );
}
