import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "src/styles/globals.css";
import classes from "./layout.module.scss";
import AppBar from "@/components/AppBar";
import TodoIcon from "@/components/TodoIcon";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={classes.backgroundColor}>
        <AppBar />
        <div className={classes.sideBar}>
          <div className={classes.ListItem}>
            <div className={classes.Frame}>
              <TodoIcon />
            </div>
            <div className={classes.ListItemText}>
              <div className={classes.Todo}>TODO</div>
            </div>
          </div>

          <div className={classes.ListItem}>
            <div className={classes.Frame}>
              <div className={classes.Icon}>
                <div className={classes.Circle}></div>
                <div className={classes.smallCircle}></div>
                <div className={classes.body}></div>
                <div className={classes.smallbody}></div>
              </div>
            </div>
            <div className={classes.ListItemText}>
              <div className={classes.Todo}>プロフィール</div>
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
